platform :ios, '14.0'

target 'Cardly-Example' do
  use_frameworks!

  # 本地引用 Pod（开发时）
  pod 'Cardly', :path => '../'

  # Example 项目业务依赖
  pod 'SnapKit'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
    end
  end
end
